version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: friday
      time: '12:00'
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: '/badge-maker'
    schedule:
      interval: weekly
      day: friday
      time: '12:00'
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: '/.github/actions/approve-bot'
    schedule:
      interval: weekly
      day: friday
      time: '12:00'
    open-pull-requests-limit: 99
